---
title: "Enunciados trabajo grupo 01"
author: "Mar Canales, Camilla Bocciolone, Manuel Triviño y Carmen Puerto"
output:
  pdf_document: 
    latex_engine: xelatex
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 1 (Mar Canales Giner)

Una empresa andaluza de artículos deportivos está considerando cuatro estrategias (D1, D2, D3, D4) bajo tres posibles escenarios de mercado (E1, E2, E3) para impulsar su presencia en el mercado del pádel. La matriz de valores numéricos (en millones de euros) bajo cada escenario viene dada en la tabla siguiente:

|        | **E1** | **E2** | **E3** |
|:------:|:------:|:------:|:------:|
| **D1** |   16   |   8    |   4    |
| **D2** |   12   |   9    |   3    |
| **D3** |   14   |   7    |   1    |
| **D4** |   10   |   6    |   2    |

## Ejercicio 2 (Mar Canales Giner)

Una agencia de viajes sevillana está decidiendo qué tipo de paquete turístico principal ofrecer el próximo año. El éxito de cada opción dependerá del nivel de demanda turística que se presente. Alternativas:\
- D1 – Ofrecer viajes internacionales\
- D2 – Potenciar viajes nacionales\
- D3 – Promocionar escapadas de fin de semana (paquetes cortos y económicos)\
Escenarios de demanda:\
• E1 – Alta demanda turística: incremento general de viajes\
• E2 – Demanda media: comportamiento normal del mercado\
• E3 – Baja demanda: caída del turismo por crisis o factores externos como la guerra\
Los siguientes valores representan los beneficios esperados (en miles de euros) para cada decisión bajo cada escenario:

|        | **E1** | **E2** | **E3** |
|:------:|:------:|:------:|:------:|
| **D1** |  300   |  180   |   60   |
| **D2** |  220   |  190   |  130   |
| **D3** |  150   |  160   |  140   |

\newpage


## Problema 1 (Camilla Bocciolone)

Aplicar los criterios de decisión bajo incertidumbre a el problema cuya tabla de decisión es la siguiente:

**favorable**

|     | E1  | E2  | E3  |
|-----|-----|-----|-----|
| D1  | 90  | 45  | -10 |
| D2  | 70  | 55  | 15  |
| D3  | 40  | 35  | 22  |

**desfavorable**

|     | E1  | E2  | E3  |
|-----|-----|-----|-----|
| D1  | -90 | -45 | 10  |
| D2  | -70 | -55 | -15 |
| D3  | -40 | -35 | -22 |

resuelverlo con cada uno de los métodos o funciones individuales de incertidumbre por separado (tanto en situación favorable como desfavorable)


## Problema 2 – Restaurante italiano y elección del menú (Camilla Bocciolone)

Un restaurante italiano debe decidir qué nuevo plato principal incluir en el menú de la próxima temporada. Las alternativas son:

-   **E1:** Lasagna vegetariana con verduras de temporada

-   **E2:** Risotto ai frutti di mare

-   **E3:** Ossobuco alla milanese con risotto a la milanesa

El éxito del plato depende de la preferencia de los clientes, es decir, de los **estados de la naturaleza**:

-   **S1:** Alta demanda de platos saludables y vegetarianos

-   **S2:** Preferencias equilibradas entre distintas opciones

-   **S3:** Mayor inclinación hacia la tradición italiana clásica

El restaurante estima los beneficios netos (en miles de euros) considerando los **ingresos obtenidos** por la venta del plato y los **costes de preparación** asociados.  
Así, por ejemplo:

- Bajo **S1**, la lasaña vegetariana (**E1**) genera ingresos de 120 000 € y tiene un coste de 40 000 €, obteniendo un beneficio de **80 000 €**.  
  En cambio, el risotto ai frutti de mare (**E2**) gana 110 000 € y gasta 40 000 €, resultando en **70 000 €**,  
  mientras que el ossobuco (**E3**) solo gana 70 000 € y gasta 40 000 €, quedando con **30 000 €**.

- Bajo **S2**, la lasaña obtiene **90 000 € de ingresos** y **40 000 € de costes**, por lo que gana **50 000 €**.  
  El risotto gana **100 000 €** y pierde **40 000 €**, quedando con **60 000 €**,  
  y el ossobuco gana **95 000 €** y pierde **40 000 €**, obteniendo **55 000 €**.
 
- Finalmente, bajo **S3**, la lasaña gana **60 000 €** y pierde **40 000 €**, quedando con **20 000 €**,  
  el risotto gana **80 000 €** y pierde **40 000 €**, quedando con **40 000 €**,  
  y el ossobuco gana **130 000 €** y pierde **40 000 €**, obteniendo **90 000 €**.

Determinar cuál es la mejor decisión para el restaurante aplicando la función R que devuelve la resolución de todos los métodos en una única tabla

\newpage


## 1. Primer problema: Resolución de tabla de decisión con los métodos vistos en clase. (Manuel Triviño)

Usaremos una tabla de decisión con los mismos datos que la tarea realizado en Excel para la clase de teoría, así podremos comparar si los resultados son iguales.

Al final de cada apartado pondremos una tabla resumen con todas las decisiones obtenidas.

|        | **E1** | **E2** | **E3** | **E4** | **E5** | **E6** |
|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| **D1** |   80   |   60   |   90   |   70   |   85   |   75   |
| **D2** |   95   |   55   |   65   |   60   |   70   |   80   |
| **D3** |   50   |   45   |   55   |   60   |   65   |   70   |
| **D4** |   90   |   85   |   95   |   80   |   75   |  100   |
| **D5** |   70   |   60   |   65   |   55   |   60   |   65   |


## 2. Segundo problema: enunciar un problema real y resolverlo mediante métodos de incertidumbre. (Manuel Triviño)

### Evaluación de pólizas de mantenimiento para vivienda.

Queremos contratar una póliza de mantenimiento anual para nuestra vivienda antes de un año con obras previstas. Hay cinco opciones comerciales disponibles: Plan Ahorro, Plan Básico, Plan Plus, Plan Premium y Plan Platinum. Cada plan establece una cuota anual fija y cubre distintos porcentajes del coste de reparaciones. Durante el año pueden ocurrir cuatro estados de la naturaleza mutuamente excluyentes:

-    **S1 Solo mantenimiento rutinario**: solo pequeñas reparaciones y revisiones por 300 €.

-    **S2 Avería de fontanería**: costes adicionales de fontanería 1.800 € más el mantenimiento rutinario.

-    **S3 Avería eléctrica y fontanería**: costes adicionales 3.000 € más el mantenimiento rutinario.

-    **S4 Daño estructural importante:** costes adicionales 9.000 € más el mantenimiento rutinario.

Las características de los planes son:

-    Plan Ahorro: cuota anual 120 €, cubre 0% de reparaciones (solo asesoramiento).

-    Plan Básico: cuota anual 300 €, cubre 50% de costes de reparaciones excepto daños estructurales (que cubre 0%).

-    Plan Plus: cuota anual 480 €, cubre 70% de fontanería y electricidad, 20% de daños estructurales.

-    Plan Premium: cuota anual 720 €, cubre 90% de fontanería y electricidad, 50% de daños estructurales.

-    Plan Platinum: cuota anual 1.200 €, cobertura completa 100% de todos los costes.

|            | **S1** | **S2** | **S3** | **S4** |
|:----------:|:------:|:------:|:------:|:------:|
| **Ahorro** |  420   | 2220   | 3420   | 9420   |
| **Básico** |  600   | 1500   | 1800   | 9900   |
| **Plus**   |  780   | 1320   | 1380   | 7740   |
| **Premium**| 1020   | 1200   | 1230   | 5220   |
| **Platinum**| 1500  | 1200   | 1200   | 1200   |


\newpage

## Ejercicio 1 (Carmen Puerto)

Un departamento universitario debe decidir qué modalidad de examen aplicar en una asignatura. La efectividad de cada decisión dependerá del nivel de preparación del alumnado ese año.

| **Estrategia (D)** | **E1 (Alumnos muy preparados)** | **E2 (Preparación media)** | **E3 (Preparación baja)** |
|:----------------|:---------------------------:|:-----------------------:|:---------------------:|
| **D1 – Examen tipo test** | 9 | 7 | 4 |
| **D2 – Examen de desarrollo** | 8 | 6 | 5 |
| **D3 – Examen mixto (test + desarrollo)** | 8 | 7 | 6 |
| **D4 – Trabajo práctico en grupo** | 6 | 8 | 7 |

Los valores representan la media esperada de calificaciones sobre 10.



## EJERCICIO 2 (Carmen Puerto)

Una persona está planificando sus vacaciones de verano. Debe elegir entre tres destinos y sabe que el disfrute del viaje dependerá del clima durante esas fechas.

| **Alternativa (D)** | **E1 (Clima soleado)** | **E2 (Clima variable)** | E3 **(Clima lluvioso)** |
|:-----------------|:------------------:|:-------------------:|:-------------------:|
| **D1 – Playa** | 9 | 6 | 2 |
| **D2 – Ciudad cultural** | 7 | 8 | 5 |
| **D3 – Turismo rural** | 6 | 7 | 8 |

Los valores representan una puntuación de satisfacción personal de 0 a 10.

